# Dockerfile for python 
# Version 1.0
FROM ubuntu:14.04

MAINTAINER Lukas Pustina <lukas.pustina@codecentric.de>

ENV DEBIAN_FRONTEND noninteractive

RUN sudo rm -rvf /var/lib/apt/lists/* 
RUN sudo  apt-get update

